name: CI

on:
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/Jod
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run prettier and eslint
        run: npm run lint && npm run check
